"""initial

Revision ID: 5432344d40f8
Revises: 
Create Date: 2026-02-14 21:11:38.867665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5432344d40f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('cat_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poet'))
    )
    op.create_index('ix_poet_name', 'poet', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('cat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poet_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cat.id'], name=op.f('fk_cat_parent_id_cat')),
    sa.ForeignKeyConstraint(['poet_id'], ['poet.id'], name=op.f('fk_cat_poet_id_poet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat'))
    )
    op.create_index('ix_cat_poet_id', 'cat', ['poet_id'], unique=False)
    op.create_index('ix_cat_poet_id_parent_id', 'cat', ['poet_id', 'parent_id'], unique=False)
    op.create_table('opinion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_opinion_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opinion'))
    )
    op.create_table('poem',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cat_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('song_last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], name=op.f('fk_poem_cat_id_cat')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poem'))
    )
    op.create_index('idx_poem_songlastchecked', 'poem', ['song_last_checked'], unique=False)
    op.create_index('ix_poem_cat_id', 'poem', ['cat_id'], unique=False)
    op.create_table('fav',
    sa.Column('poem_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], name=op.f('fk_fav_poem_id_poem')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_fav_user_id_user')),
    sa.PrimaryKeyConstraint('poem_id', 'user_id', name=op.f('pk_fav')),
    sa.UniqueConstraint('poem_id', 'user_id', name='uq_fav_poem_user')
    )
    op.create_index('ix_fav_poem_id', 'fav', ['poem_id'], unique=False)
    op.create_index('ix_fav_user_id', 'fav', ['user_id'], unique=False)
    op.create_table('omen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poem_id', sa.BigInteger(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], name=op.f('fk_omen_poem_id_poem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omen'))
    )
    op.create_index('ix_omen_poem_id', 'omen', ['poem_id'], unique=False)
    op.create_table('poemsnd',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poem_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('dnldurl', sa.Text(), nullable=True),
    sa.Column('audio_order', sa.BigInteger(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('recitation_type', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], name=op.f('fk_poemsnd_poem_id_poem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poemsnd'))
    )
    op.create_index('ix_poemsnd_poem_id_audio_order', 'poemsnd', ['poem_id', 'audio_order'], unique=False)
    op.create_table('song',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poem_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], name=op.f('fk_song_poem_id_poem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song'))
    )
    op.create_index('ix_song_poem_id', 'song', ['poem_id'], unique=False)
    op.create_table('verse',
    sa.Column('poem_id', sa.BigInteger(), nullable=False),
    sa.Column('vorder', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], name=op.f('fk_verse_poem_id_poem')),
    sa.PrimaryKeyConstraint('poem_id', 'vorder', name=op.f('pk_verse'))
    )
    op.create_index('ix_verse_poem_id', 'verse', ['poem_id'], unique=False)
    op.create_index('ix_verse_poem_id_vorder', 'verse', ['poem_id', 'vorder'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verse_poem_id_vorder', table_name='verse')
    op.drop_index('ix_verse_poem_id', table_name='verse')
    op.drop_table('verse')
    op.drop_index('ix_song_poem_id', table_name='song')
    op.drop_table('song')
    op.drop_index('ix_poemsnd_poem_id_audio_order', table_name='poemsnd')
    op.drop_table('poemsnd')
    op.drop_index('ix_omen_poem_id', table_name='omen')
    op.drop_table('omen')
    op.drop_index('ix_fav_user_id', table_name='fav')
    op.drop_index('ix_fav_poem_id', table_name='fav')
    op.drop_table('fav')
    op.drop_index('ix_poem_cat_id', table_name='poem')
    op.drop_index('idx_poem_songlastchecked', table_name='poem')
    op.drop_table('poem')
    op.drop_table('opinion')
    op.drop_index('ix_cat_poet_id_parent_id', table_name='cat')
    op.drop_index('ix_cat_poet_id', table_name='cat')
    op.drop_table('cat')
    op.drop_table('user')
    op.drop_index('ix_poet_name', table_name='poet')
    op.drop_table('poet')
    # ### end Alembic commands ###
